# Generated by Django 4.1 on 2022-11-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0007_proxy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="key_help_link",
            field=models.URLField(
                blank=True, help_text="Link for software Help Button"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="key_info",
            field=models.CharField(
                blank=True, help_text="License Keys information text", max_length=1000
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="url",
            field=models.URLField(
                help_text="Link where users should get their license keys",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="messagebox",
            name="text",
            field=models.TextField(
                help_text="Text shown when users launch the app", max_length=10000
            ),
        ),
    ]
